#!/bin/sh

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop aesdsocket server
### END INIT INFO

# Path to your aesdsocket application
DAEMON=/usr/bin/aesdsocket
PIDFILE=/var/run/aesdsocket.pid

start() {
    echo "Starting aesdsocket server"
    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- -d
}

stop() {
    echo "Stopping aesdsocket server"
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload|force-reload)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
