name: assignment-test
on: 
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:

        container: cuaesd/aesd-autotest:assignment5

        #container: cuaesd/aesd-autotest:assignment1
    #container: cuaesd/aesd-autotest:assignment2
        #72adb1697ec689eb5a5a406095e49ce27d6ecb74
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
